spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090

eureka:
  instance:
    hostname: discovery-server
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans

springdoc:
  swagger-ui:
    urls:
      - name: player
        url: /v3/api-docs/player
      - name: tournament
        url: /v3/api-docs/tournament
      - name: venue
        url: /v3/api-docs/venue
        