spring:
    boot:
    admin:
      client:
        url: http://admin-server:9090

management:
  endpoints:
    web:
      exposure:
        include: '*'

eureka:
  instance:
    hostname: discovery-server
    preferIpAddress: true
