spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090

  kafka:
    producer:
      bootstrap-servers: broker:29092

  data:
    redis:
      host: player-redis
      port: 6379

  datasource:
    url: jdbc:postgresql://player-postgres-db:5432/player
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    hostname: discovery-server
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    root: INFO
    za.co.ishe.tchess: DEBUG
    io.micrometer: DEBUG
    org.springframework.aop: DEBUG
  console:
    enabled: true

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
