server:
  port: 7777

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    za.co.ishe.tchess: DEBUG
    io.micrometer: DEBUG
    org.springframework.aop: DEBUG

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6370

  datasource:
    url: jdbc:postgresql://localhost:54320/player
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      file: ./docker/compose.yml

  kafka:
    producer:
      client-id: player-producer
      bootstrap-servers: localhost:9092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      properties:
        spring:
          json:
            type:
              mapping: event:za.co.ishe.tchess.player.event.PlayerCreatedEvent

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    url: /openapi.yml

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
