server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    io:
      micrometer: DEBUG
    org:
      springframework.aop: DEBUG

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

  datasource:
    url: jdbc:postgresql://localhost:5432/tchess
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    url: /player-api.yml

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
