spring:
  boot:
    admin:
      client:
        url: http://admin-server

  kafka:
    producer:
      bootstrap-servers: broker:29092

  datasource:
    url: jdbc:postgresql://postgres-db/tchess
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

eureka:
  instance:
    hostname: discovery-server
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
