spring:
  boot:
    admin:
      client:
        url: http://admin-server:9090

  datasource:
    url: jdbc:postgresql://tournament-postgres-db:54322/tournament
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      enabled: false

eureka:
  instance:
    hostname: discovery-server
    preferIpAddress: true
  client:
    service-url:
      defaultZone: http://discovery-server:8761/eureka

management:
  zipkin:
    tracing:
      endpoint: http://zipkin-server:9411/api/v2/spans
