server:
  port: 0

management:
  endpoints:
    web:
      exposure:
        include: '*'
  tracing:
    sampling:
      probability: 1.0

logging:
  pattern:
    level: '%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]'
  level:
    io:
      micrometer: DEBUG
    org:
      springframework.aop: DEBUG

spring:
  boot:
    admin:
      client:
        url: http://localhost:9090

  cache:
    type: redis

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    url: jdbc:postgresql://localhost:54321/venue
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver

  docker:
    compose:
      file: ./docker/compose.yml

  jpa:
    show-sql: true
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: create

  sql:
    init:
      mode: always

springdoc:
  swagger-ui:
    url: /openapi.yml

eureka:
  instance:
    hostname: localhost
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
